task :default => :run

desc "compile simple.pegjs"
task :simple do 
  sh "pegcoffee simple.pegjs"
end

task :runsimple do
  sh "coffee use_simple.coffee"
end

desc "Compile with pegcoffee cplusplus.pegjs"
task :compilegrammar do 
  sh "pegcoffee cplusplus.pegjs"
end

desc "Compile use_cplusplus.coffee to js"
task :compilemain => [:compilegrammar] do
  sh "coffee -c use_cplusplus.coffee"
end

desc "Compile use_cplusplus.coffee to js"
task :run => [:compilemain] do
  sh "node use_cplusplus.js"
end


desc "Compile leftrec.jison and run main_leftrec.js"
task :leftrec do
  sh "jison leftrec.jison"
  sh "node main_leftrec.js"
end
