task :default => :run

desc "compile simple.pegjs"
task :simple do 
  sh "pegjs --plugin pegjs-coffee-plugin simple.pegjs"
end

desc "compile remove_left_recursive.pegjs"
task :removeleft do 
  sh "pegjs --plugin pegjs-coffee-plugin remove_left_recursive.pegjs"
  sh "coffee use_remove_left.coffee"
end

task :runsimple do
  sh "coffee use_simple.coffee"
end

desc "Compile with pegjs --plugin pegjs-coffee-plugin cplusplus.pegjs"
task :compilegrammar do 
  sh "pegjs --plugin pegjs-coffee-plugin cplusplus.pegjs"
end

desc "Compile use_cplusplus.coffee to js"
task :compilemain => [:compilegrammar] do
  sh "coffee -c use_cplusplus.coffee"
end

desc "Compile use_cplusplus.coffee to js"
task :run => [:compilemain] do
  sh "node use_cplusplus.js"
end


desc "Compile leftrec.jison and run main_leftrec.js"
task :leftrec do
  sh "jison leftrec.jison"
  sh "node main_leftrec.js"
end
